/*
  ==============================================================================

    PatreonBackers.h

    Special thanks to our Patreon supporters who make these plugins possible!

    ⚠  IMPORTANT: this file exists in THREE git worktrees and must stay in sync:
        - plugins/plugins/shared/PatreonBackers.h                (main)
        - plugins-worktree/plugins/shared/PatreonBackers.h
        - plugins-multi-synth/plugins/shared/PatreonBackers.h
    Whichever worktree you edit, copy the change to the other two before
    rebuilding; otherwise plugins built from different worktrees will show
    inconsistent credits.

    To add new backers:
    1. Add names to the appropriate tier array below
    2. Copy this file to the other two worktrees (see paths above)
    3. Rebuild all plugins

    Tier Benefits:
    - Hugs ($1/month):       Development updates, name in credits
    - Supporter ($3/month):  Development updates, name in credits
    - Patron ($5/month):     Development updates, name in credits
    - Champion ($10/month):  Development updates, name in credits

  ==============================================================================
*/

#pragma once

// Support both JuceHeader.h (generated by juce_generate_juce_header) and direct module includes
#if __has_include(<JuceHeader.h>)
    #include <JuceHeader.h>
#else
    #include <juce_core/juce_core.h>
#endif

#include <vector>

namespace PatreonCredits
{
    //==========================================================================
    // Backer Lists
    //==========================================================================

    // Champion ($10/month)
    inline const std::vector<juce::String> champions = {
    };

    // Patron ($5/month)
    inline const std::vector<juce::String> patrons = {
        "David",
    };

    // Supporter ($3/month)
    inline const std::vector<juce::String> supporters = {
        "Eblen Macari",
        "Jano",
        "Manav",
        "Someone64",
        "Stefan Windus",
    };

    // Hugs ($1/month)
    inline const std::vector<juce::String> hugs = {
        "Adrienne",
        "mister-universe",
    };

    // Past Supporters — thank you for your support!
    inline const std::vector<juce::String> pastSupporters = {
        "S C",
    };

    //==========================================================================
    // Helper Functions
    //==========================================================================

    /** Get all backers formatted for display in credits/about dialogs */
    inline juce::String getAllBackersFormatted()
    {
        juce::String result;

        if (!champions.empty())
        {
            result += "CHAMPIONS\n\n";
            for (const auto& name : champions)
                result += name + "\n";
            result += "\n";
        }

        if (!patrons.empty())
        {
            result += "PATRONS\n\n";
            for (const auto& name : patrons)
                result += name + "\n";
            result += "\n";
        }

        if (!supporters.empty())
        {
            result += "SUPPORTERS\n\n";
            for (const auto& name : supporters)
                result += name + "\n";
        }

        if (!hugs.empty())
        {
            result += "\nHUGS\n\n";
            for (const auto& name : hugs)
                result += name + "\n";
        }

        if (!pastSupporters.empty())
        {
            result += "\nPAST SUPPORTERS\n\n";
            for (const auto& name : pastSupporters)
                result += name + "\n";
        }

        if (result.isEmpty())
            result = "Be the first to support development on Patreon!\n\nYour name could be here!";

        return result;
    }

    /** Get total number of backers across all tiers */
    inline int getTotalBackerCount()
    {
        return static_cast<int>(champions.size() + patrons.size() +
                                supporters.size() + hugs.size() +
                                pastSupporters.size());
    }
}
