// SPDX-License-Identifier: GPL-3.0-or-later

#include "CabinetLibrary.h"
#include "CabinetIR.h"

// BinaryData header is generated by juce_add_binary_data when at least one
// resource is present. Use __has_include so the plugin still builds when
// resources/cabs/ is empty (e.g. on a fresh checkout before licensing
// clears) — in that case every loadInto() call falls back to "(none)".
#if __has_include("BinaryData.h")
    #include "BinaryData.h"
    #define DUSKAMP_HAS_BUNDLED_CABS 1
#else
    #define DUSKAMP_HAS_BUNDLED_CABS 0
#endif

namespace CabinetLibrary
{
    namespace
    {
        // The catalog. To add a new bundled cabinet:
        //   1) drop the .wav into plugins/DuskAmp/resources/cabs/
        //   2) ensure the filename (minus extension) matches binarySymbol
        //      below; JUCE replaces non-alphanumerics with underscores
        //   3) add an enum value to CabinetId in CabinetLibrary.h
        //   4) add an entry here
        //   5) document the file's licensing in resources/cabs/LICENSES.md
        const Entry kEntries[] =
        {
            { None,                     "(none)",                       "" },
            { FenderTwin_SM57,          "Fender Twin — SM57",           "fender_twin_sm57_oa" },
            { Marshall1960VB_SM57_OA,   "Marshall 1960VB — SM57 OA",    "marshall_1960vb_sm57_oa" },
            { Marshall1960VB_SM57_Off,  "Marshall 1960VB — SM57 Off",   "marshall_1960vb_sm57_off" },
            { VoxAC15_SM57,             "Vox AC15 — SM57",              "vox_ac15_sm57" },
            { VoxAC15_sE4_Close,        "Vox AC15 — sE4 Close",         "vox_ac15_se4_close" },
        };

        static_assert (sizeof (kEntries) / sizeof (kEntries[0]) == static_cast<size_t> (Count),
                       "kEntries must list every CabinetId exactly once");

        // Resolve a binary-symbol stem to a (data, size) pair, or {nullptr, 0}
        // if the file wasn't bundled at build time. JUCE's juce_add_binary_data
        // emits two symbols per file (<stem>_wav + <stem>_wavSize) plus a
        // runtime lookup helper getNamedResource(name, size) that returns
        // nullptr for missing resources — exactly what we want for graceful
        // partial-set behaviour.
        struct Bytes { const char* data; int size; };

        Bytes resolveSymbol (const char* binarySymbol)
        {
            if (binarySymbol == nullptr || binarySymbol[0] == '\0')
                return { nullptr, 0 };

#if DUSKAMP_HAS_BUNDLED_CABS
            // Convention: source filename "<stem>.wav" → JUCE symbol
            // "<stem>_wav" (non-alphanumerics replaced with underscores).
            const juce::String resourceName = juce::String (binarySymbol) + "_wav";
            int   size = 0;
            const char* data = BinaryData::getNamedResource (resourceName.toRawUTF8(), size);
            if (data != nullptr && size > 0)
                return { data, size };
#endif
            return { nullptr, 0 };
        }
    }

    juce::Span<const Entry> entries()
    {
        return { kEntries, sizeof (kEntries) / sizeof (kEntries[0]) };
    }

    int numChoices()
    {
        return static_cast<int> (Count);
    }

    juce::String displayNameForChoice (int choiceIndex)
    {
        if (choiceIndex < 0 || choiceIndex >= static_cast<int> (Count))
            return "(unknown)";
        return juce::String (kEntries[choiceIndex].displayName);
    }

    bool loadInto (CabinetIR& cabinet, int choiceIndex)
    {
        if (choiceIndex <= 0 || choiceIndex >= static_cast<int> (Count))
            return false;   // None or out-of-range — leave existing IR

        const Entry& entry = kEntries[choiceIndex];
        Bytes bytes = resolveSymbol (entry.binarySymbol);

        if (bytes.data == nullptr || bytes.size <= 0)
            return false;   // file not bundled in this build

        cabinet.loadIRFromMemory (bytes.data,
                                   static_cast<size_t> (bytes.size),
                                   juce::String (entry.displayName));
        return true;
    }
}
